version: '3'

service:
 app:
   build: .
   ports:
    - 3000:3000
   volumes:
    - .:home/node/app
   mysql:
    image: 
    mysql: mysql:community-server
    
    environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: nest